version: "3.8"

services:
  frontend:
    build:
      context: ./ecommerce-dashboard
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./ecommerce-backend
    ports:
      - "5000:5000"
