
### API Endpoints for products ----------------------------------------------------
GET http://localhost:5000/api/products
###
GET http://localhost:5000/api/products/68389955d299e87d9cf0e92d
###
POST http://localhost:5000/api/products
Content-Type: application/json

{
    "name":"Cheese",
    "price": "49",
    "stock": "10",
    "description": "limited addition",
    "category": "Food"
}
###
DELETE http://localhost:5000/api/products/Cheese
###


### API Endpoints for category ----------------------------------------------------

### Add New Category Document
POST http://localhost:5000/api/categories
Content-Type: application/json

{
  "name": "School"
}

### Get All Category Documents
GET http://localhost:5000/api/categories

### Update a Category Document by ID
PUT http://localhost:5000/api/categories/category/update/683938f56bd66819066eac35
Content-Type: application/json

{
  "name":"school"
}

### Delete a Category Document by ID
DELETE http://localhost:5000/api/categories/categories/683938f56bd66819066eac35
###




### Order API endpoints -----------------------------------------------------------

### Retrieve all orders in database
GET http://localhost:5000/api/orders

### Create New Order 
POST http://localhost:5000/api/orders
Content-Type: application/json

{
  "userId": "60c72b2f9e1d4c4f887fd123",
  "products": [
    {
      "productId": "60c72b559e1d4c4f887fd124",
      "quantity": 2
    },
    {
      "productId": "60c72b559e1d4c4f887fd125",
      "quantity": 1
    }
  ],
  "total": 150
}

### Get All Orders by User ID
GET http://localhost:5000/api/orders/user/60c72b2f9e1d4c4f887fd123

### Update Order Status
PUT http://localhost:5000/api/orders/683939136bd66819066eac42
Content-Type: application/json

{
  "status": "Shipped"
}

### Delete Order
DELETE http://localhost:5000/api/orders/683939136bd66819066eac42





### Review API endpoints------------------------------------------->

### Retrieve all reviews in database
GET http://localhost:5000/api/reviews

### Create New Review
POST http://localhost:5000/api/reviews
Content-Type: application/json

{
  "userId": "66506bd26b0d18f6b70d333e",
  "rating": 5,
  "comment": "Great product!"
}

### Update review
PUT http://localhost:5000/api/reviews/66506bd26b0d18f6b70d333e/0
Content-Type: application/json

{
  "rating": 5,
  "comment": "Updated: Even better than before!"
}


### Delete Review
DELETE http://localhost:5000/api/reviews/66506bd26b0d18f6b70d333e/0




###transaction api endpoints------------------------------------------>

### Retrieve all transactions in database
GET http://localhost:5000/api/transactions


### Create New Transaction
POST http://localhost:5000/api/transactions
Content-Type: application/json

{
  "userId": "66506bd26b0d18f6b70d215a",
  "transaction": {
    "products": [
      {
        "productId": "665070246b0d18f6b70d215c",
        "quantity": 2,
        "price": 50
      }
    ],
    "totalAmount": 100,
    "paymentMethod": "Card",
    "paymentStatus": "Paid"
  }
}








