
### API Endpoints for products ----------------------------------------------------
GET http://localhost:5000/api/products
###

GET http://localhost:5000/api/localhost:3000/users
###
POST http://localhost:5000/api/products
Content-Type: application/json

{
    "name":"Cheese",
    "price": "49",
    "stock": "10",
    "description": "Is a wonderful thing",
    "category": "Dairy"
}
###
POST http://localhost:5000/api/products
Content-Type: application/json

{
    "name":"Milk",
    "price": "30",
    "stock": "20",
    "description": "Tasty",
    "category": "Dairy"
}
###
DELETE http://localhost:5000/api/products/DickCheese
###



### API Endpoints for category ----------------------------------------------------

### Add New Category Document
POST http://localhost:5000/api/categories
Content-Type: application/json

{
  "categories": [
    { "name": "Dairy", "quantity": 10 },
    { "name": "Meats", "quantity": 5 },
    { "name": "Fruits", "quantity": 15 }
  ]
}

### Get All Category Documents
GET http://localhost:5000/api/categories

### Update a Category Document by ID
PUT http://localhost:5000/api/categories/category/update/6834534b45f1268d805dc104
Content-Type: application/json

{
  "categories": [
    {
      "CatId": "60c72b559e1d4c4f887fd321",
      "quantity": 20
    }
  ]
}

### Delete a Category Document by ID
DELETE http://localhost:5000/api/categories/categories/6834534b45f1268d805dc108
###




### Order API endpoints -----------------------------------------------------------

### Retrieve all orders in database
GET http://localhost:5000/api/orders

### Create New Order 
POST http://localhost:5000/api/orders
Content-Type: application/json

{
  "userId": "60c72b2f9e1d4c4f887fd123",
  "products": [
    {
      "productId": "60c72b559e1d4c4f887fd124",
      "quantity": 2
    },
    {
      "productId": "60c72b559e1d4c4f887fd125",
      "quantity": 1
    }
  ],
  "total": 150
}

### Get All Orders by User ID
GET http://localhost:5000/api/orders/user/6834639992b385f4d35031a7

### Update Order Status
PUT http://localhost:5000/api/orders/6835a64ba4aee8a63d348ec4
Content-Type: application/json

{
  "status": "Shipped"
}

### Delete Order
DELETE http://localhost:5000/api/orders/6834648992b385f4d35031b9

### Review API endpoints------------------------------------------->

### Retrieve all reviews in database
GET http://localhost:5000/api/reviews

### Create New Review
POST http://localhost:5000/api/reviews
Content-Type: application/json

{
  "userId": "66506bd26b0d18f6b70d215e",
  "reviews": [
    {
      "rating": 4,
      "comment": "Great product!"
    }
  ]
}
### Update review
PUT http://localhost:5000/api/reviews/66506bd26b0d18f6b70d215e
Content-Type: application/json

{
  "reviews": [
    {
      "rating": 5,
      "comment": "Updated: Even better than before!"
    }
  ]
}

### Delete Review
DELETE http://localhost:5000/api/reviews/66506bd26b0d18f6b70d215e

###transaction api endpoints------------------------------------------>

### Retrieve all transactions in database
GET http://localhost:5000/api/transactions


### Create New Transaction
POST http://localhost:5000/api/transactions
Content-Type: application/json

{
  "userId": "66506bd26b0d18f6b70d215a",
  "transaction": [
    {
      "amount": 100.0,
      "currency": "USD",
      "type": "deposit"
    }
  ]
}

### Update transaction
PUT http://localhost:5000/api/transactions/66506bd26b0d18f6b70d215a
Content-Type: application/json

{
  "userId": "66506bd26b0d18f6b70d215a",
  "transaction": [
    {
      "amount": 150.0,
      "currency": "USD",
      "type": "deposit"
    }
  ]
}

###delete transaction
DELETE http://localhost:5000/api/transactions/66506bd26b0d18f6b70d215a






